repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: sort-simple-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: detect-private-key
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: "5.6.4"
    hooks:
      - id: isort
        additional_dependencies:
          - toml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
      - id: mypy
